### ISSUE TITLE
Protocol Docs

### ISSUE THREAD

**Issue by bkanuka** [claudegel/sinope-gt125#10]
Do you have any documentation for this binary protocol?

I'm working on separating the gt125 code from home assistant code so the gt125 code can be used as a library in other projects

**Comment by claudegel** [comment]
Yes I've doc from Sinopé and also you can look in my other repo sinope-1/custom_component/testing. There is a python file that I've used to develop this Sinope-gt125. I'm presently working on my component to be able to listen to the GT125 to catch the event sent by the switch and light. Instead of poking the GT125 to get the status of a light I'll be able to just wait for event sent by the devices when someone open or close a light, or a switch.

**Comment by claudegel** [comment]
I'll send you the doc by email
