### ISSUE TITLE
issue Error code: 7ffc

### ISSUE THREAD

**Issue by olivierjag2** [claudegel/sinope-gt125#46]
Hi

I have many error message, do you have idea?

Logger: custom_components.sinope
Source: custom_components/sinope/__init__.py:281 
Integration: Sinope GT125 (documentation) 
First occurred: 02:01:04 (1358 occurrences) 
Last logged: 11:03:44

Error code: 7ffc (None or invalid value for 9aa40100), Data:(550015004102248129500a01009aa40100070802000002fc7f4f)
Error code: 7ffc (None or invalid value for bda60100), Data:(550015004102564277400a0100bda60100070802000002fc7faf)
Error code: 7ffc (None or invalid value for 5ebb0000), Data:(550015004102348457490a01005ebb0000070802000002fc7f60)
Error code: 7ffc (None or invalid value for 45ff0000), Data:(550015004102331685930a010045ff0000070802000002fc7f6d)
Error code: 7ffc (None or invalid value for 9efe0000), Data:(550015004102156114230a01009efe0000070802000002fc7fa2)

**Comment by claudegel** [comment]
Let me decode your Data to see what's wrong

**Comment by claudegel** [comment]
Ok the data you received was for a data read request to get room setpoint on your thermostats.
550015004102248129500a01009aa40100070802000002fc7f4f
This goes like this:
5500: preambule
1500: data length
4102: command answer for data request 4002.
24812950: control sequence to identify that specific request so the response goes to the wright request
0a0100: 0a, status of the request = OK , 01 number of attempt done (00, 01, 02), 00 how many more answer will come back
9aa40100: your device ID
07: length of the data answered
08020000: Data type ID, room setpoint
02: Data size
fc7f: data which is the bad data answer you got 7ffc
4f: crc check
So it look like the device is not able to send the room setpoint. Was it during a DR period and are you registered with Éco Sinopé ?
The value 7ffc instead of a setpoint value is for: No value / Invalid / Disabled 
look like thermostats were not able to respond.

**Comment by olivierjag2** [comment]
J'ai désactiver sinope eco et j'ai encore le même code d'erreur

**Comment by olivierjag2** [comment]
Logger: custom_components.sinope
Source: custom_components/sinope/__init__.py:281 
Integration: Sinope GT125 (documentation) 
First occurred: 02:00:37 (737 occurrences) 
Last logged: 10:11:26

Error code: 7ffc (None or invalid value for 5ebb0000), Data:(550015004102988319910a01005ebb0000070802000002fc7fbf)
Error code: 7ffc (None or invalid value for 9aa40100), Data:(550015004102926670680a01009aa40100070802000002fc7f51)
Error code: 7ffc (None or invalid value for bda60100), Data:(550015004102215658300a0100bda60100070802000002fc7f36)
Error code: 7ffc (None or invalid value for 5ebb0000), Data:(550015004102428914100a01005ebb0000070802000002fc7fa8)
Error code: 7ffc (None or invalid value for 9aa40100), Data:(550015004102292915980a01009aa40100070802000002fc7ff5

**Comment by claudegel** [comment]
J'ai demandé à Sinopé pourquoi certains thermostats retournent l'erreur 7ffc au lieu de la température de consigne. J'ai remarqué que lorsqu'une DR est actif, le setpoint de certains thermostats indique la mauvaise valeur directement sur l'appareil. J'ai un thermostat de plancher qui est ajusté à 18oC en période DR mais quand j'appuis sur le bouton pour voir le setpoint ca me dit 10oC. Je sais que Sinopé est à faire plein de modification sur les appareils pour le Éco Sinopé. Il y a plein de paramètres qui s'ajoutent et/ou changent de nom. Possiblement que ceci en est la cause. 
L'erreur concerne l'info retournée pour la valeur du setpoint. Ca ne dois pas affecter le comportement du thermostat. On demande au thermostat son setpoint au cas ou quelqu'un aurait changé manuellement le setpoint pour synchroniser HA.
Même si Éco Sinopé est désactivé c'est juste un parametre qui est a off mais le thermostat reçoit quand même les commandes de Éco Sinopé.

Quel model de thermostat est-ce et est-ce que les erreurs arrivent pendant une période DR. Il suffirait possiblement de ne pas faire de demande pour le setpoint pendant une période DR. Il se peut que le thermostat ne réponde pas à cette demande en période DR.
