### ISSUE TITLE
Unable to execute device.py

### ISSUE THREAD

**Issue by sbeaudoin** [claudegel/sinope-gt125#52]
Followed instructions to install the integration v1.5.7 on home assistant OS v9.4.  I try to execute the following command to be able to get the API key required for the configuration.yaml file.

`sudo python3 device.py`

Both sudo and python3 gives "command not found".

How can I execute this script to retrieve the API key?

**Comment by sbeaudoin** [comment]
Is this still maintained?

**Comment by claudegel** [comment]
Sorry didn't see your issue. Was busy in another module. It is still maintained. Let me check.

**Comment by claudegel** [comment]
To run device.py you need first to be in the directory where the file is located.
so open the terminal in HA and `cd config/custom_components/sinope`
Then execute the commande `sudo python3 device.py`
You can also do `sudo python device.py` it will work
I'll update the README.MD 
Did you install via HACS or manually

**Comment by claudegel** [comment]
Normally I get an email when somebody open an issue but this is not working for this repo. I'll check to activate the email when somebody open an issue or do a PR

**Comment by claudegel** [comment]
If you need more help please fell free to reopen that issue.
best thing is to install via HACS to make sure file permission are ok then follow what I've sed above.
Sorry for having missed your issue.

**Comment by sbeaudoin** [comment]
Also sorry for my delay.  I solved it by running device.py on my windows machine ans some modifications.  But your instructions still don't work for others who would want to execute it on HA : 
![image](https://user-images.githubusercontent.com/3873484/223699436-cade18f3-ce10-4313-9a0f-4820097ea8b1.png)

**Comment by claudegel** [comment]
Are you on Hass.io or another home assistant os.
In Hass.io (supervised) it work like this sudo python device.py. But it also work with python device.py or python3 device.py or python3.10 device.py.
it is possible that on your system your user has already the permission to execute device.py so no need for sudo.
For the python command it is normally a sym link to the real command that should be something like python3 or python3.10
If none of them work then python is not installed on your os.
It should be a good thing for all others to show how to install python in order to run device.py.
can you try apk add --no-cache python3
You are accessing your HA via ssh. Do you have the addon ssh and web terminal installed. This provide a terminal directly inside HA and this is the way I access device.py
![sinope](https://user-images.githubusercontent.com/4268938/223911659-c3768b15-9d31-4b55-9eb3-9d54d93f8994.jpg)

**Comment by jessemcdowell** [comment]
I had this same problem, and it took me a while to figure out what was going on. Being completely new to Home Assistant I just assumed I could use the "Terminal & SSH" add-on, but you really can't. You need to use "SSH & Web Terminal" which has full access to the system including the ability to run Python. I had some trouble setting that up too, but that's an issue for another place.

**Comment by claudegel** [comment]
So do you still have problem to run python device.py. In ssh & web terminal it works but in Terminal & SSH python is not found.
I've updated documentation to specify using ssh & web terminal
